forward: false
fwi: true
vmin: 1.377
vmax: 4.688
opt_meth: 'LBFGS'
mute_depth: 12

# checkpointing parameters
ckp_params:
  checkpointing: false
  ckptype: "MULTILEVEL_CKP"
  pct_ckp: null
  pct_mckp: 0.05
  singlefile: False
  costs_mem: [5, 4]
  costs_disk: [100, 50]
  
# geometry
file_src: null
file_rec: null
nshots: 16 
src_depth: 40.
src_step: 1133.
nrecs: 426
rec_depth: 80.
model_size: 17000.0

# solver parameters
solver_params:
  shotfile_path: "./"
  parfile_path: "./marmousi2/parameters_hdf5/"
  setup_func: "tti"
  t0: 0.0
  tn: 5000.0 
  dt: 4.0
  f0: 0.004 
  model_name: "marmousi2" 
  nbl: 50
  space_order: 8
  born: false
  dtype: "float32"

# dask cluster
use_local_cluster: True
queue: "GPUlongB"
project: "cenpes-lde"
n_workers: 4
cores: 1
processes: 1
memory: 2
shot_batch_size: 4
extra_job:
  - '-e slurm-%j.err'
  - '-o slurm-%j.out'
  - '--time=72:00:00'
  - '--requeue'
  - '--job-name="dask-modeling"'
