cores: 1
extra_job: [-e slurm-%j.err, -o slurm-%j.out, '--time=72:00:00', --requeue, --job-name="dask-modeling"]
file_rec: null
file_src: null
memory: 2
model_size: 4600.0
n_workers: 4
nrecs: 369
nshots: 184
processes: 1
project: cenpes-lde
queue: GPUlongB
rec_depth: 12.5
shot_batch_size: 4
solver_params: {dt: 4.0, dtype: float32, f0: 0.008, model_name: marmousi, nbl: 50,
  parfile_path: ./marmousi/parameters_hdf5/, shotfile_path: ./, space_order: 8, t0: 0.0,
  tn: 2500.0, use_solver: true}
src_depth: 12.5
src_step: 25.0
use_local_cluster: true
